I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 45, in script
    faye "Hey, no - what photos?"
Exception: Sayer 'faye' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 45, in script
    faye "Hey, no - what photos?"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'faye' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Practicing Safe Sex(t): The Game 1.0
Thu Feb  3 12:38:02 2022
